# Generated by Django 5.1.7 on 2025-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='processed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
