# Generated by Django 5.1.7 on 2025-03-24 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_log_processed_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.destination'),
        ),
    ]
