# Generated by Django 5.1.7 on 2025-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_log_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='received_timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
